# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: valuePlaceHolder # from-param: ${service-name}
  labels:
    role: api
    team: sre
    cloud.googleapis.com/location: northamerica-northeast1
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: valuePlaceHolder # from-param: ${cloudsql-instances}
        autoscaling.knative.dev/maxScale: valuePlaceHolder # from-param: ${max-scale}
    spec:
      containerConcurrency: valuePlaceHolder # from-param: ${container-concurrency}
      timeoutSeconds: valuePlaceHolder # from-param: ${timeout-seconds}
      containers:
      - name: valuePlaceHolder # from-param: ${container-name}
        image: image-placeholder
        ports:
        - name: http1
          containerPort: valuePlaceHolder # from-param: ${container-port}
        env:
        - name: APP_ENV
          value: valuePlaceHolder # from-param: ${app-env}
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      #  volumeMounts:
      #  - mountPath: /devops/oas
      #    name: oas_proxy
      #- name: prism
      #  image: stoplight/prism:4
      #  command:
      #  - mock -h 0.0.0.0 /tmp/api.oas3.yml
      #  resources:
      #    limits:
      #      cpu: 500m
      #      memory: 256Mi
      #  volumeMounts:
      #  - mountPath: /tmp
      #    readOnly: true
      #    name: oas_proxy
      #volumes:
      #- name: oas_proxy
      #  emptyDir:
      #    medium: Memory
      #    sizeLimit: 5Mi