apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "bcregistry-cronjob.fullname" . }}
  labels:
    {{- include "bcregistry-cronjob.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy | quote }}
  suspend: false
  jobTemplate:
    metadata:
      labels:
        {{- include "bcregistry-cronjob.labels" . | nindent 8 }}
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            {{- include "bcregistry-cronjob.labels" . | nindent 12 }}
        spec:
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
          {{- end }}
          {{- if .Values.securityContext }}
          {{- if .Values.securityContext.runAsUser }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            {{- if .Values.securityContext.runAsGroup }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            {{- end }}
            {{- if .Values.securityContext.fsGroup }}
            fsGroup: {{ .Values.securityContext.fsGroup }}
            {{- end }}
          {{- end }}
          {{- end }}
          containers:
            - name:  {{ include "bcregistry-cronjob.fullname" . }}
              image: {{ include "bcregistry-cronjob.image" . }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: {{ .Values.command }}
              {{- if .Values.envFrom.secretRef }}
              envFrom:
                - secretRef:
                    name: {{ include "bcregistry-cronjob.secretName" . }}
              {{- end }}
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 1600
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
