apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bcregistry-cronjob.fullname" . }}-secret
  labels:
    {{- include "bcregistry-cronjob.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $index, $val := .Values.env }}
  {{- if .secure }}
  {{ $index | kebabcase }}: {{ .value | b64enc | quote }}
  {{ end }}
{{ end }}
