# Default values for bcregistry-queue.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: "dev"
role: "queue"

image:
  repository: "image-registry.openshift-image-registry.svc:5000"
  namespace: "73c567-tools"
  pullPolicy: "IfNotPresent"
  digest: "sha256:953e89d9882cf710750ee760e557d8b49381691fe6bee0bbe9675de1c6679b6e"
  tag: "dev"

imagePullSecrets: []

migrations:
  enabled: true
  command: "/opt/app-root/pre-hook-update-db.sh"

ports:
  containerPort: 8080
  protocol: TCP

resources: {}

replicas: 1

revisionHistoryLimit: 10

livenessProbe:
  httpGet:
    path: /healthz
    port: 7070
    scheme: HTTP
  initialDelaySeconds: 3
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /readyz
    port: 7070
    scheme: HTTP
  initialDelaySeconds: 3
  timeoutSeconds: 30
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

args: {}

env:
  {}
  # SOME_ENV_VAR:
  #   value: "var2"
  #   secure: false
  # SOME_SEC_ENV_VAR:
  #   value: "var"
  #   secure: true

envFrom:
  secretRef: ture

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP

autoscaling:
  # Specifies whether the autoscaling should be created
  create: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
