name: 'Terraform-GCS'

on:
  workflow_dispatch:
    inputs:
      terraform_directory:
        description: 'Path to Terraform directory'
        required: true
        type: string
        default: 'gcp/terraform'
      workspace:
        description: 'Terraform workspace (dev|test|prod|other|default|all)'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
          - other
          - mpf
          - default
          - all
        default: 'dev'
      action:
        description: 'Terraform action to run'
        required: true
        type: choice
        options:
          - plan
          - apply
        default: 'plan'

env:
  TF_VAR_DB_ROLE_MANAGEMENT_SERVICE_ACCOUNT_EMAIL: ${{ secrets.TF_VAR_DB_ROLE_MANAGEMENT_SERVICE_ACCOUNT_EMAIL }}

  STATE_BUCKET: 'common-tools-terraform-state'
  STATE_PREFIX: 'iam'

permissions:
  contents: read
  id-token: write   # required for Workload Identity Federation

jobs:
  terraform:
    name: 'Terraform - ${{ inputs.workspace }}'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ secrets.TFC_GCP_WORKLOAD_PROVIDER_NAME }}
        service_account: ${{ secrets.TF_VAR_DB_ROLE_MANAGEMENT_SERVICE_ACCOUNT_EMAIL }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.10.5
        terraform_wrapper: false

    - name: Clear Terraform cache
      run: |
        rm -rf ~/.terraform.d/
        rm -rf ~/.terraformrc
        rm -rf .terraform/
        rm -f .terraform.lock.hcl
      working-directory: ${{ inputs.terraform_directory }}

    - name: Terraform Init
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform init \
          -backend-config="bucket=${{ env.STATE_BUCKET }}" \
          -backend-config="prefix=${{ env.STATE_PREFIX }}" \
          -reconfigure \
          -input=false

    - name: Terraform ${{ inputs.action }}
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        if [ "${{ inputs.action }}" == "apply" ]; then
          ./tf.sh apply ${{ inputs.workspace }} -auto-approve
        else
          ./tf.sh plan ${{ inputs.workspace }}
        fi
